version: "3.8"
services:
  db:
   image: 192.168.0.2:5050/dedyms/mariadb:10.6
   volumes:
     - db:/var/lib/mysql
   ports:
     - 3310:3306
   environment:
     - MARIADB_ROOT_PASSWORD=blokcyroot
     - TZ=Asia/Jakarta
     - MARIADB_DATABASE=blocky
     - MARIADB_USER=blockyuser
     - MARIADB_PASSWORD=blockypass
   deploy:
     placement:
       constraints: [node.role==manager]
   networks:
     - blocky

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
#    ports:
#      - 9090:9090
    restart: always
    networks:
      - blocky
    deploy:
      placement:
        constraints: [node.role==manager]

  # dont use latest, grafana 9 breaks sql queries.
  grafana:
    image: grafana/grafana:9.2.1
    depends_on:
      - prometheus
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: always
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
      - blocky

volumes:
    prometheus_data:
    grafana_data:
    db:

networks:
  blocky:
    name: blocky
