---
version: "3.5"
services:
#  web:
#    image: martadinata666/nginx:xdebug
#    volumes:
#      - ./htdocs:/var/www/html
#      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
#      - ./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
#    ports:
#      - 20000:80
#    networks:
#      - code-server
#    deploy:
#      placement:
#        constraints: [ node.hostname == homelab  ]
  app:
    image: 192.168.0.2:5050/dedyms/code-server:latest
    volumes:
      - ./data:/home/debian/code-server
      - /home/dedyms/Documents/docker-gitlab-local:/home/debian/code-server/docker-gitlab
      - /home/dedyms/.ssh:/home/debian/.ssh
#      - ./htdocs:/var/www/html
    #ports:
    #  - 9003:9003
    #  - 5555:5555
    #  - 5500:5500
    networks:
      - code-server
    deploy:
      placement:
        constraints: [ node.hostname == homelab  ]

  nginx:
    image: 192.168.0.2:5050/dedyms/nginx:mainline
    ports:
      - 4000:443
    configs:
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - code-server

networks:
  code-server:
    name: code-server

configs:
  default.conf:
    file: ./default.conf
