version: "3.8"
services:
  app:
    image: 192.168.0.2:5050/dedyms/beatbump:git
#     image: beatbump:local
#    command: bash
#    tty: true
#    stdin_open: true
    networks:
      - beatbump
    ports:
      - "17000:3000"
    restart: always

networks:
  beatbump:
    name: beatbump