version: "3.8"
services:
  app:
    image: 192.168.0.2:5050/dedyms/beatbump:git
    networks:
      - beatbump
    ports:
      - 17000:3000
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]

  proxy:
    image: 192.168.0.2:5050/dedyms/beatbump:proxy-rust
    ports:
      - 21000:10000
    networks:
      - beatbump
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  beatbump:
    name: beatbump