version: "3.8"
services:
  app:
    image: 192.168.0.2:5050/dedyms/beatbump:git
    networks:
      - beatbump
    ports:
      - 17000:3000
    restart: always

  proxy:
    image: 192.168.0.2:5050/dedyms/beatbump:proxy
    ports:
      - 21000:3001
    networks:
      - beatbump

networks:
  beatbump:
    name: beatbump