version: "3.8"
services:
  app:
    #image: nitnelave/lldap:latest
    image: 192.168.0.2:5050/dedyms/lldap:v0.4.0
    restart: unless-stopped
    ports:
      # For LDAP
      - "3890:3890"
      # For LDAPS
      - "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - ./data:/data	
      # Alternatively, you can mount a local folder
    environment:
      - TZ=Asia/Jakarta
      - LLDAP_JWT_SECRET=thisisjwtsecret
      - LLDAP_LDAP_USER_PASS=ldappass
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
      - lldap

networks:
  lldap:
    name: lldap
