version: "3.8"
services:
  app:
    image: nitnelave/lldap:latest
    restart: unless-stopped
    ports:
      # For LDAP
      - "3890:3890"
      # For the web front-end
      - "17170:17170"
    volumes:
      - ./data:/data	
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      - TZ=Asia/Jakarta
      - LLDAP_JWT_SECRET=thisisjwtsecret
      - LLDAP_LDAP_USER_PASS=ldappass
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
    deploy:
      placement:
        constraints: [node.role==manager]
