version: '3.8'
services:
  app:
    image: 192.168.0.2:5050/dedyms/libreddit:latest
    networks:
      - libreddit
    deploy:
       mode: global
#      placement:
#        constraints: [ node.hostname == rpi4 ]
  apache:
    image: 192.168.0.2:5050/dedyms/apache:fcgid
    ports:
      - 8282:443
    configs:
      - source: apache.conf
        target: /etc/apache2/sites-available/000-default-ssl.conf
    networks:
      - libreddit
    deploy:
       mode: global
#      placement:
#        constraints: [ node.hostname == rpi4 ]
networks:
  libreddit:
    name: libreddit

configs:
  apache.conf:
    file: ./000-default.conf
