version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/qbittorrent-nox:latest
    #entrypoint: /home/debian/.local/bin/qbittorrent-nox --webui-port=8090 --profile=/home/debian/qbittorrent
    #command: bash
    #tty: true
    #stdin_open: true
    environment:
      - TZ=Asia/Jakarta
      - WEBPORT=8090
    volumes:
      - ./config:/home/debian/qbittorrent
      - nfs-downloads:/home/debian/downloads
      - cifs-wd:/home/debian/WD
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8090:8090
    restart: unless-stopped
    networks:
      - qbittorrent
    #  - swag
    deploy:
      placement:
        constraints: [node.hostname == homelab]

networks:
  qbittorrent:
    name: qbittorrent

volumes:
  nfs-config:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,rsize=8192,wsize=8192,timeo=14,nolock"
      device: ":/home/dedyms/docker/qbittorrent-nox/config"
  nfs-downloads:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock,rsize=8192,wsize=8192"
      device: ":/media/Clouds/Downloads/Torrents"
  cifs-wd:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.0.2/datashare
      o: "username=dedyms,password=smb,file_mode=0700,dir_mode=0700,uid=1000,gid=1000,vers=3.0"
