version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/whoogle:v0.7.4
    volumes:
      - config:/home/debian/whoogle/config
    environment:
      - WHOOGLE_CONFIG_NEW_TAB=true
      - WHOOGLE_CONFIG_DISABLE=true
      - WHOOGLE_CONFIG_THEME=dark
      - WHOOGLE_AUTOCOMPLETE=1
      - WHOOGLE_CONFIG_URL=https://192.168.0.2:5000
      - HTTPS_ONLY=1
    #command: bash
    #stdin_open: true
    #tty: true
    #ports:
    #  - 5000:5000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.hostname == homelab ]
    networks:
      - whoogle

  apache:
    image: 192.168.0.2:5050/dedyms/apache:fcgid
    ports:
      - 5000:443
    configs:
      - source: apache.conf
        target: /etc/apache2/sites-available/000-default-ssl.conf
    networks:
      - whoogle


volumes:
  config:

networks:
  whoogle:
    name: whoogle

configs:
  apache.conf:
    file: ./apache.conf
