---
version: '3.5'
services:
  app:
    image: 192.168.0.2:5050/dedyms/ympd:v0.23.8
    volumes:
      - mpd-data:/home/debian/mpd
      - nfs-music:/music
    networks:
      - ympd
    restart: always
    #environment:
    #  MPD_SERVER: player
    #  MPD_PORT: 6600
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 8083:8080
      - 8800:8800
      - 8000:8000
    deploy:
      placement:
        constraints:
          - node.hostname == homelab

volumes:
  icecast2-config:
  mpd-data:
  nfs-music:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,rsize=8192,wsize=8192,timeo=14,nolock"
      device: ":/home/dedyms/Musik/Music"

networks:
  ympd:
    name: ympd
#  icecast2:
#    external: true
