---
version: '3.5'
services:
  app:
    image: 192.168.0.2:5050/dedyms/ympd:latest
    volumes:
      - mpd-data:/home/debian/mpd
      - nfs-music:/music
      - ./conf:/home/debian/mympd
    networks:
      - ympd
    restart: always
    #environment:
    #  MPD_SERVER: player
    #  MPD_PORT: 6600
    #  - MYMPD_HTTP_PORT=8084
    #  - MYMPD_SSL=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      # MPD port
      - 6600:6600
      # ympd web port
      - 8083:8080
      # http output
      - 8800:8800
      # icecast output
      - 8000:8000
    deploy:
      placement:
        constraints:
          - node.hostname == homelab

  maloja:
    image: krateng/maloja
    user: 1000:1000
    volumes:
      - ./scrobble:/scrobble
    environment:
      - MALOJA_DATA_DIRECTORY=/scrobble
    ports:
      - 42010:42010
    deploy:
      placement:
        constraints:
          - node.hostname == homelab

# docker run -p 42010:42010 -v $PWD/malojadata:/mljdata -e MALOJA_DATA_DIRECTORY=/mljdata krateng/maloja

volumes:
  icecast2-config:
  mpd-data:
  nfs-music:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,rsize=8192,wsize=8192,timeo=14,nolock"
      device: ":/home/dedyms/Musik/Music"

networks:
  ympd:
    name: ympd
#  icecast2:
#    external: true
