version: "3.5"
services:
  web:
    image: 192.168.0.2:5050/dedyms/nginx:mainline-fpm7
    volumes:
      - ./htdocs:/var/www/html
      - /media/Clouds/InstaSave:/var/www/html/photos
      #- ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - photoshow
    ports:
      - 9090:80
    restart: always

networks:
  photoshow:
    name: photoshow
