version: "3.5"
services:
  notify:
    image: 192.168.0.2:5050/dedyms/apprise:latest
    ports:
      - 1000:8000
    environment:
      - APPRISE_WORKER_COUNT=1
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - apprise

networks:
  apprise:
    name: apprise
