---
version: "3.5"
services:
  db:
     image: postgres:13
     user: 1000:1000
     environment:
       - POSTGRES_USER=heimdall
       - POSTGRES_DB=heimdall
       - POSTGRES_PASSWORD=heimdallpass
     volumes:
       - ./db:/var/lib/postgresql/data
     networks:
       - heimdall
     deploy:
       placement:
         constraints: [ node.role == manager ]

  rd:
    #image: redis:latest
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - df-db:/data
    restart: unless-stopped
    networks:
      - heimdall
    deploy:
      placement:
        constraints: [node.hostname == homelab ]

  web:
    image: 192.168.0.2:5050/dedyms/heimdall:2.5.6
    networks:
      - heimdall
    configs:
      - source: env
        target: /var/www/html/.env
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
      - source: sslcrt
        target: /etc/ssl/localcerts/nginx.crt
      - source: sslkey
        target: /etc/ssl/localcerts/nginx.key
    volumes:
      - nfs-storage:/var/www/html/storage
      #- nfs-htdocs:/var/www/html
    deploy:
      placement:
        constraints: [ node.role == manager ]
    environment:
      - APP_NAME=Dashboard
      - TZ=Asia/Jakarta
    ports:
      - 80:80
      - 443:443

networks:
  heimdall:
    name: heimdall
#  swag:
#    external: true

configs:
  env:
    file: env
  nginx:
    file: nginx.conf
  sslcrt:
    file: ssl/homelab.crt
  sslkey:
    file: ssl/homelab.key
volumes:
  rd:
  df-db:
  nfs-db:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/heimdall/db"
  nfs-storage:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/heimdall/storage"
  #nfs-htdocs:
  #  driver_opts:
  #    type: "nfs4"
  #    o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
  #    device: ":/home/dedyms/docker/heimdall/htdocs242"
