version: "3.5"
services:
  es:
    image: opensearchproject/opensearch:1
    environment:
      - discovery.type=single-node
      - TZ=Asia/Jakarta
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
    user: 1000:1000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./dataes:/usr/share/elasticsearch/data
    networks:
      - diskover
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

  app:
    image: 192.168.0.2:5050/dedyms/diskover-ce:latest
    environment:
      - TZ=Asia/Jakarta
      - ES_HOST=es
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=changeme
    volumes:
      - /media/WD:/media/WD
      - ./database:/var/www/html/database
    networks:
      - diskover
    ports:
      - 12000:8000
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

networks:
  diskover:
    name: diskover

#volumes:
#  htdocs:

#configs:
#  nginx.conf:
#    file: ./diskover-nginx.conf
