---
version: "3.5"
services:
  web:
    image: plexinc/pms-docker:plexpass
    container_name: plex_mediaserver
#    ports:
#      - 32400:32400
#      - 1900:1900
    environment:
      - TZ=Asia/Jakarta
      - PLEX_UID=1000
      - PLEX_GID=1000
      - ADVERTISE_IP=http://192.168.0.2:32400
#      - PLEX_CLAIM="claim-_Wx2B1ttJyC_Kr4DFczn"
    volumes:
      - ./data:/config
      - /dev/shm:/transcode
      - /media/WD:/media/WD
      - /media/Clouds:/media/Clouds
    network_mode: host
    devices:
      - /dev/dri/:/dev/dri/
    restart: always
volumes:
  transcode:
