#docker run \
#    -v /path/to/root:/srv \
#    -v /path/filebrowser.db:/database.db \
#    -v /path/.filebrowser.json:/.filebrowser.json \
#    -u $(id -u):$(id -g) \
#    -p 8080:80 \
#    filebrowser/filebrowser

version: "3.8"
services:
  app:
    image: filebrowser/filebrowser:latest
    user: 1000:1000
    volumes:
      - ./db:/db
      - ow_videos:/srv/videos
      - /media/WD/Videos/AnimeX:/srv/animeX
#      - /home/dedyms/docker/shinobi/videos/dms:/srv
#      - /media/Clouds:/srv/clouds
#      - /home/dedyms/docker/shinobi/videos:/srv/cctv
#      - /media/hgst:/srv/hgst
      - ./filebrowser.json:/.filebrowser.json
    ports:
      - 1100:80
    networks:
      - filebrowser
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  filebrowser:
    name: filebrowser

volumes:
  ow_videos:
    external: true