version: '3.9'

services:
  manager:
#    image: 192.168.0.2:5050/dedyms/docker-swarm-visualizer-rs:git
#    user: root
    image: yandeu/visualizer-rs:dev
#    tty: true
#    stdin_open: true
#    command: bash
    environment:
      - VISUALIZER_TYPE=manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    labels:
      - visualizer.manager
    ports:
      - 9510:9510
    healthcheck:
      test: curl -f http://localhost:9510/healthcheck || exit 1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

  agent:
    image: 192.168.0.2:5050/dedyms/docker-swarm-visualizer-rs:git
    user: root
    environment:
      - VISUALIZER_TYPE=agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    labels:
      - visualizer.agent
    healthcheck:
      test: curl -f http://localhost:9511/healthcheck || exit 1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

networks:
  agent_network:
    driver: overlay
    attachable: true
