#docker run --name some-guacd -d -p 4822:4822 guacamole/guacd
version: "3.5"
services:
   guacd:
     image: martadinata666/guacd:git
     networks:
       - guacamole
     #ports:
     #  - 4822:4822
     deploy:
       placement:
         constraints: [ node.role == manager ]
   guacamole:
     image: martadinata666/guacamole:git
     environment:
       - POSTGRES_HOSTNAME=db
       - POSTGRES_USER=guacamole
       - POSTGRES_DATABASE=guacamole
       - POSTGRES_PASSWORD=guacamolepass
       # REPLACE POSTGRES with MYSQL
       - GUACD_HOSTNAME=guacd
     #volumes:
     #  - ./init:/init
     #ports:
     #  - 4822:8080
     # /opt/guacamole/bin/initdb.sh --postgres > initdb.sql
     # /opt/guacamole/bin/initdb.sh --mysql > initdb.sql
     # psql -U guacamole guacamole < /init/initdb.sql
     # psql -U postgres-user postgres-db-name < /init/initdb.sql
     # mysql -u username -p database_name < /path/to/file.sql
     networks:
       - guacamole
     deploy:
       placement:
         constraints: [ node.hostname == rpi4 ]
   db:
     image: postgres:13
     environment:
       - POSTGRES_USER=guacamole
       - POSTGRES_DB=guacamole
       - POSTGRES_PASSWORD=guacamolepass
     volumes:
       - ./db:/var/lib/postgresql/data
       - ./init:/init
       - ./backup:/backup
     networks:
       - guacamole
     deploy:
       placement:
         constraints: [ node.role == manager ]

   apache:
     image: 192.168.0.2:5050/dedyms/apache:fcgid
     networks:
       - guacamole
     configs:
       - source: apache.conf
         target: /etc/apache2/sites-available/000-default-ssl.conf
     ports:
       - 4822:443
     deploy:
       placement:
         constraints: [ node.role == manager ]

networks:
  guacamole:
    name: guacamole

configs:
  apache.conf:
    file: ./apache.conf
