version: "3.5"
services:
  rd:
   image: redis:alpine
   #image: dph5199278/dragonflydb:latest
   environment:
     - TZ=Asia/Jakarta
   volumes:
     - rd:/data
   restart: unless-stopped
   networks:
     - linkace
   deploy:
     placement:
       constraints: [node.hostname == homelab ]

  db:
   image: 192.168.0.2:5050/dedyms/mariadb:10.7
   user: 1000:1000
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
   environment:
      - MARIADB_ROOT_PASSWORD=mariadblinkace
      - TZ=Asia/Jakarta
      - MARIADB_DATABASE=linkace
      - MARIADB_USER=linkace
      - MARIADB_PASSWORD=linkace
   volumes:
      - nfs-db:/var/lib/mysql
   restart: unless-stopped
   networks:
      - linkace
   deploy:
     placement:
       constraints: [ node.role == manager ]
  web:
   image: 192.168.0.2:5050/dedyms/linkace:latest
   environment:
     - TZ=Asia/Jakarta
     - APP_TIMEZONE=Asia/Jakarta
   volumes:
     - ./env:/var/www/html/.env
     - ./backups:/var/www/html/storage/app/backups
   networks:
     - linkace
   ports:
     - 7070:443
   deploy:
     placement:
       constraints: [ node.hostname == homelab ]
   restart: unless-stopped
networks:
  linkace:
    name: linkace
volumes:
  rd:
#  nfs-htdocs:
#    driver_opts:
#      type: "nfs4"
#      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
#      device: ":/home/dedyms/docker/linkace/htdocs1.9"
  nfs-db:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/linkace/db"
