version: "3"
services:
  app:
    image: quay.io/invidious/invidious:latest
    networks:
      - invidious
    restart: unless-stopped
    ports:
      - "35000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: db
          port: 5432
        check_tables: true
        domain:
        https_only: false
        external_port:
        popular_enabled: true
        statistics_enabled: false
        registration_enabled: true
        login_enabled: true
        captcha_enabled: true
        channel_threads: 1
        feed_threads: 1
        enable_user_notifications: false
        hmac_key: 61fe63584295750bcd93ffdcaa4a26e1d600d6c7
        default_user_preferences:
          locale: en-US
          region: US
          #captions: ["", "", ""]
          dark_mode: true
          thin_mode: false
          feed_menu: ["Popular", "Trending", "Subscriptions", "Playlists"]
          default_home: Trending
          related_videos: true
          autoplay: false
#    healthcheck:
#      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
#      interval: 30s
#      timeout: 5s
#      retries: 2
    depends_on:
      - invidious-db
    labels:
      - com.centurylinklabs.watchtower.enable=true
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

  db:
    image: docker.io/library/postgres:13
    user: 1000:1000
    networks:
      - invidious
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./config/init-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

networks:
 invidious:
   name: invidious

