version: '3'
services:
  db:
    restart: always
    user: 1000:1000
    image: postgres:13
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mastodon

#  db-setup:
#    image: ghcr.io/mastodon/mastodon:v4.1.2
#    restart: "no"
#    env_file: mastodon.env
#    command: bundle exec rake db:setup && bundle exec rake db:migrate
#    depends_on:
#      - db
#    networks:
#      - mastodon

  redis:
    restart: always
    image: redis:latest
    #image: docker.dragonflydb.io/dragonflydb/dragonfly
    #image: cachegrand/cachegrand-server:latest
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - internal_network
    #healthcheck:
    #  test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - redis:/data

  web:
    image: ghcr.io/mastodon/mastodon:v4.1.2
#    user: 1000:1000
    restart: always
    env_file: mastodon.env
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rake db:migrate && bundle exec rails s -p 3000"
    networks:
      - internal_network
      - external_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    ports:
      - '30000:3000'
    depends_on:
      - db
      - redis
    volumes:
      - ./system:/mastodon/public/system
      - ./cleanup.sh:/usr/local/bin/mastodon-cleanup

  streaming:
    image: ghcr.io/mastodon/mastodon:v4.1.2
    user: 1000:1000
    restart: always
    env_file: mastodon.env
    command: node ./streaming
    networks:
      - internal_network
      - external_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    ports:
      - 4000:4000
    depends_on:
      - db
      - redis

  sidekiq:
    image: ghcr.io/mastodon/mastodon:v4.1.2
#    user: 1000:1000
    restart: always
    env_file: mastodon.env
    command: bundle exec sidekiq -c 15
    depends_on:
      - db
      - redis
    networks:
      - internal_network
      - external_network
    volumes:
      - ./system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

networks:
  internal_network:
    internal: true
  external_network:

volumes:
  redis:
