version: "2.1"
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
#    command: sh
#    tty: true
#    stdin_open: true
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=UTC # Optional to synchronize the log timestamp with host
    volumes:
      # config file
      - ./config.yml:/app/config.yml
