version: "3.8"
services:
  web:
    image: 192.168.0.2:5050/dedyms/nextcloud-smb:26.0.2
    environment:
      - TZ=Asia/Jakarta
      - ALLOW_SELF_SIGNED=true
      - NEXTCLOUD_URL=https://nextcloud.ddyms.space
#      - NEXTCLOUD_UPDATE=0
    volumes:
      - htdocs:/var/www/html
      - nfs-cl-pictures:/Pictures
      - nfs-cl-instasave:/InstaSave
      - nfs-config:/var/www/html/config
      - nfs-data:/var/www/html/data
      - nfs-themes:/var/www/html/themes
      - nfs-custom_apps:/var/www/html/custom_apps
      - ./ssl/nextcloud.crt:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./ssl/nextcloud.key:/etc/ssl/private/ssl-cert-snakeoil.key
      - ./ldap.conf:/etc/ldap/ldap.conf
    #configs:
    #  - source: user.ini
    #    target: /var/www/html/.user.ini
    ports:
      - 8081:8080
      - 8080:8443
    restart: unless-stopped
    networks:
      - nextcloud
      - minio
      - lldap
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]
#  es:
#    image: opensearchproject/opensearch:1
#    environment:
#      - discovery.type=single-node
#      - TZ=Asia/Jakarta
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - xpack.security.enabled=true # this is elastic config
#      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
#      - "DISABLE_SECURITY_PLUGIN=true" # Disables security plugin
#    user: 1000:1000
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - nextcloud
#    volumes:
#      - ./osdata/data:/usr/share/opensearch/data
#      - ./osdata/plugins:/usr/share/opensearch/plugins
#      - ./esdata/data:/usr/share/elasticsearch/data
#      - ./esdata/plugins:/usr/share/elasticsearch/plugins
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

  db:
    image: 192.168.0.2:5050/dedyms/mariadb:lts
    environment:
      #- MARIADB_AUTO_UPGRADE=1
      - MARIADB_ROOT_PASSWORD=mariadbnc
      - TZ=Asia/Jakarta
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=nextcloud
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - nextcloud
    deploy:
      placement:
        constraints: [ node.role == manager ]

  imaginary:
    image: nextcloud/aio-imaginary:latest
    restart: always
    environment:
      - PORT=9000
      - TZ=Asia/Jakarta
    networks:
      - nextcloud
    deploy:
      placement:
        constraints: [node.role == manager]
#    command: -concurrency 50 -enable-url-source -log-level debug
#  drawio:
#    user: 1000:1000
#    image: jgraph/drawio:latest
#    environment:
#      - TZ=Asia/Jakarta
#    ports:
#      - 8082:8080
  #  restart: unless-stopped
#    networks:
#      - nextcloud
#    deploy:
#      placement:
#         constraints: [node.hostname == homelab ]
  rd:
    #image: docker.dragonflydb.io/dragonflydb/dragonfly
    image: redis:latest
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - rd-data:/data
    restart: unless-stopped
    networks:
      - nextcloud
    deploy:
      placement:
        constraints: [node.hostname == homelab ]

volumes:
  htdocs:
  rd-data:
  df-data:
  db:
#  ds_logs:
#  ds_data:
  nfs-cl-pictures:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/media/Clouds/Pictures/dedyms"
  nfs-cl-instasave:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/media/Clouds/InstaSave"
  nfs-config:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/nextcloud/config"
  nfs-data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/nextcloud/data"
  nfs-themes:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/nextcloud/themes"
  nfs-custom_apps:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/nextcloud/custom_apps"

networks:
  nextcloud:
    name: nextcloud
  lldap:
    external: true
  minio:
    external: true

#configs:
#  varnish.vcl:
#    file: varnish.vcl
#  nginx.conf:
#    file: nginx.conf
#  apache.conf:
#    file: apache.conf
