version: "3.3"
services:
  homepage:
    image: martadinata666/homepage:main
    container_name: homepage
    ports:
      - 3500:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations