version: "3.8"
services:

  redis:
    image: redis:6.2
    restart: always

  database:
    image: postgres:14
    user: 1000:1000
    environment:
      - POSTGRES_PASSWORD=immichpass
      - POSTGRES_USER=immichuser
      - POSTGRES_DB=immich
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always


  microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - /media/WD/Rasdem/Photos:/usr/src/app/upload
    env_file:
      - env.immich
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - /media/WD/Rasdem/Photos:/usr/src/app/upload
    env_file:
      - env.immich
    environment:
      - NODE_ENV=production
    ports:
      - 2281:3001
    depends_on:
      - redis
      - database
    restart: always

  web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - env.immich
    ports:
      - 2282:3000
    environment:
      # Rename these values for svelte public interface
      - PUBLIC_IMMICH_SERVER_URL=http://192.168.0.2:2281
      # - IMMICH_WEB_URL=http://192.168.0.2:2282
      # - IMMICH_SERVER_URL=http://server:3001
    restart: always

  immich-proxy:
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL=http://server:3001
      - IMMICH_WEB_URL=http://web:3000
    ports:
      - 2283:8080
    depends_on:
      - server
    restart: always
