version: "3.8"
services:
  app:
    image: 192.168.0.2:5050/dedyms/ping:bullseye
    environment:
      - URL=cbn.id
    networks:
      - ping
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  ping:
    name: ping
