version: "3.8"
services:
  app:
    image: 192.168.0.2:5050/dedyms/reactive-resume:v3.6.8
#    command: bash
#    tty: true
#    stdin_open: true
    restart: always
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - env.v3
    networks:
      - resume
    volumes:
      - nfs-uploads:/home/debian/reactiveresume/server/dist/assets/uploads
      - nfs-exports:/home/debian/reactiveresume/server/dist/assets/exports
    ports:
      - 3000:3000
      - 3100:3100
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

  db:
    image: postgres:13
    user: 1000:1000
    environment:
      - POSTGRES_USER=reactiveresume
      - POSTGRES_PASSWORD=reactiveresumepass
      - POSTGRES_DB=reactiveresume
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - resume
    deploy:
      placement:
        constraints: [ node.role == manager ]

networks:
  resume:
    name: resume

volumes:
  nfs-uploads:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/resume/assets/uploads"
  nfs-exports:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/resume/assets/exports"

configs:
  nginx.conf:
    file: nginx.conf
