---
version: "3.5"
services:
  db:
    image: 192.168.0.2:5050/dedyms/mariadb:10.7
    environment:
      - MARIADB_ROOT_PASSWORD=documizeroot
      - TZ=Asia/Jakarta
      - MARIADB_DATABASE=documize
      - MARIADB_USER=documize
      - MARIADB_PASSWORD=documize
      - MARIADB_AUTO_UPGRADE=0
    volumes:
      - nfs-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - documize
    deploy:
      placement:
        constraints: [ node.role == manager ]
  app:
    image: 192.168.0.2:5050/dedyms/documize:latest
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - nfs-config:/home/debian/documize
    ports:
      - 5001:5001
    networks:
      - documize
    depends_on:
      - db
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]
  nginx:
    image: 192.168.0.2:5050/dedyms/nginx:mainline
    ports:
      - 5002:443
    configs:
      - source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - documize
  #apache:
  #  image: 192.168.0.2:5050/dedyms/apache:fcgid
  #  ports:
  #    - 5003:443
  #  configs:
  #    - source: apache.conf
  #      target: /etc/apache2/sites-available/000-default-ssl.conf
  #  networks:
  #    - documize

networks:
  documize:
    name: documize

volumes:
  nfs-config:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/documize/data"
  nfs-db:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/documize/db"
configs:
  nginx.conf:
    file: ./default.conf
  apache.conf:
    file: ./000-default.conf

