---
version: "3.5"
services:
  client:
    image: 192.168.0.2:5050/dedyms/glances:client
    volumes:
      - ./glances-client.conf:/home/debian/glances/glances.conf
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - glances

  wetty:
    user: 1000:1000
    image: wettyoss/wetty
    command: --ssh-host=client --ssh-port=2222 --ssh-user=debian --ssh-pass=debian --base / --title glances-client -c "glances --disable-autodiscover -C /home/debian/glances/glances.conf --browser"
    #command: --ssh-host=client --ssh-port=2222 --ssh-user=debian --ssh-pass=debian --base / --title glances-client
    ports:
      - 3105:3000
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - glances

  server-homelab:
    image: 192.168.0.2:5050/dedyms/glances:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADDITIONAL_OPT=-d -s
    ports:
      - 61200:61208
    networks:
      - glances
    deploy:
      placement:
        constraints: [node.hostname == homelab ]

  server-rpi4:
    image: 192.168.0.2:5050/dedyms/glances:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADDITIONAL_OPT=-d -s
    ports:
      - 61201:61208
    networks:
      - glances
    deploy:
      placement:
        constraints: [node.hostname == rpi4 ]

  server-gitlab:
    image: 192.168.0.2:5050/dedyms/glances:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADDITIONAL_OPT=-d -s
    ports:
      - 61202:61208
    networks:
      - glances
    deploy:
      placement:
        constraints: [node.hostname == GITLAB ]

networks:
  glances:
    name: glances
