version: "3.2"
services:
  buildx-volume-prune:
    image: 192.168.0.2:5050/dedyms/docker-static:latest
    command: ["sh","-c","docker volume prune --filter all=1 -f"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=5 0 * * *"
        - "swarm.cronjob.skip-running=false"
        - "swarm.cronjob.replicas=1"
      restart_policy:
        condition: none
    networks:
      - cronjob
networks:
  cronjob:
    external: true
