version: "3.2"
services:
  system-prune:
    image: 192.168.0.2:5050/dedyms/docker-static:latest
    command: ["sh","-c","docker system prune -f && docker image prune -a -f"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=10 0 * * *"
        - "swarm.cronjob.skip-running=false"
        - "swarm.cronjob.replicas=1"
      restart_policy:
        condition: none
    networks:
      - cronjob
networks:
  cronjob:
    external: true
