version: "3.5"
services:
  app:
    image: crazymax/swarm-cronjob
#    user: 1000:1000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      #- "TZ=Asia/Jakarta"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    networks:
      - cronjob
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  cronjob:
    name: cronjob
