---
version: "3.8"
services:
  server:
    image: 192.168.0.2:5050/dedyms/jellyfin:stable
    runtime: youki
    security_opt:
      - seccomp=unconfined
    container_name: jellyfin_server
    pull_policy: always
    #entrypoint: ./jellyfin/jellyfin --datadir /config --cachedir /cache --ffmpeg /usr/lib/jellyfin-ffmpeg/ffmpeg
    environment:
      - TZ=Asia/Jakarta
    group_add:
      - "44"
      - "139"
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8097:8097
    volumes:
      - ./config:/config
      - ./config/subtitle:/Subtitle Edit/Dictionaries
      - cache:/cache
      - /media/WD/Videos:/Videos:rw
      - ow_videos:/Videos2:rw
      - /media/Clouds/Porn:/Porn:rw
      - transcodes:/config/transcodes
      - /home/dedyms/docker/shinobi/videos/dms/office:/c1c
      - /home/dedyms/docker/shinobi/videos/dms/office2:/c6n
    networks:
      - jellyfin
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2000M

volumes:
  cache:
  ow_videos:
    external: true
  transcodes:

networks:
  jellyfin:
    name: jellyfin
