---
version: "3.8"
services:
  server:
    image: 192.168.0.2:5050/dedyms/jellyfin:git
    container_name: jellyfin_server
    #entrypoint: ./jellyfin/jellyfin --datadir /config --cachedir /cache --ffmpeg /usr/lib/jellyfin-ffmpeg/ffmpeg
    hostname: homelab
    environment:
      - TZ=Asia/Jakarta
    #group_add:
    #  - video
    #  - render
    devices:
      - /dev/dri/:/dev/dri/
    ports:
      - 8097:8096
    volumes:
      - ./config:/config
      - cache:/cache
      - /media/WD/Videos:/Videos:rw
      - ow_videos:/Videos2:rw
      - /media/Clouds/Porn:/Porn:rw
      - ./transcodes:/config/transcodes
    networks:
      - jellyfin
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    #deploy:
    #  placement:
    #    constrainst: [ node.name == homeworker0 ]
  client:
    image: 192.168.0.2:5050/dedyms/jellyfin-vue:static
    container_name: jellyfin_client
    ports:
      - 8098:80
    networks:
      - jellyfin
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
volumes:
  cache:
  ow_videos:
    external: true
  #transcodes:
  #nfs-data:
  #  driver_opts:
  #    type: "nfs4"
  #    o: "addr=192.168.0.3,rw,noatime,timeo=14,nolock"
  #    device: ":/home/dedyms/docker/jellyfin/data"
  #nfs-cache:
  #  driver_opts:
  #    type: "nfs4"
  #    o: "addr=192.168.0.3,rw,noatime,timeo=14,nolock"
  #    device: ":/home/dedyms/docker/jellyfin/cache"
networks:
  jellyfin:
    name: jellyfin
