version: "3.8"
services:
  web:
    image: 192.168.0.2:5050/dedyms/apache:fpm
    volumes:
      - ./grav:/var/www/html
    ports:
      - 7000:80
    networks:
      - grav
    deploy:
      placement:
        constraints: [node.role==manager]

networks:
  grav:
    name: grav

