version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/plex-discord-bot:git
    restart: always
#    volumes:
#      - ./config/keys.js:/home/PlexBot/config/keys.js
#      - ./config/plex.js:/home/PlexBot/config/plex.js
#      - ./config/config.js:/home/PlexBot/config/config.js
    configs:
      - source: plex.js
        target: /home/debian/plex-discord-bot/config/plex.js
      - source: keys.js
        target: /home/debian/plex-discord-bot/config/keys.js
      - source: config.js
        target: /home/debian/plex-discord-bot/config/config.js
    deploy:
      placement:
         constraints: [node.hostname==homelab]

configs:
  keys.js:
    file: ./config/keys.js
  plex.js:
    file: ./config/plex.js
  config.js:
    file: ./config/config.js
