version: "3.8"
services:
  db:
   image: 192.168.0.2:5050/dedyms/mariadb:lts
   command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
   environment:
      - MARIADB_ROOT_PASSWORD=huginnroot
      - TZ=Asia/Jakarta
      - MARIADB_DATABASE=huginn
      - MARIADB_USER=huginnuser
      - MARIADB_PASSWORD=huginnpass
      - MARIADB_INITDB_SKIP_TZINFO=1
   volumes:
      - db:/var/lib/mysql
   restart: always
   networks:
      - huginn

  app:
    image: martadinata666/huginn:develop
    volumes:
      - ./env:/app/.env
    restart: always
    ports:
      - 29100:80
    networks:
      - huginn

volumes:
  db:

networks:
  huginn:
    name: huginn
