version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/uptime-kuma:1.17.0
    volumes:
      - ./data:/home/debian/uptime-kuma/data
    deploy:
      placement:
        constraints: [ node.hostname == homelab  ]
    environment:
      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libeatmydata.so
    networks:
      - kuma
    #ports:
    #  - 3001:3001
  apache:
    image: 192.168.0.2:5050/dedyms/apache:fcgid
    ports:
      - 9400:443
      #- 9443:80
    configs:
      - source: apache.conf
        target: /etc/apache2/sites-available/000-default.conf
      - source: apache-ssl.conf
        target: /etc/apache2/sites-available/000-default-ssl.conf
    networks:
      - kuma

volumes:
  data:
networks:
  kuma:
    name: kuma
  #goautentik:
  #  external: true
configs:
  apache.conf:
    file: ./apache.conf
  apache-ssl.conf:
    file: ./apache-ssl.conf
