#docker run \
#  -p 9000:9000 \
#  -p 9001:9001 \
#  -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
#  -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
#  quay.io/minio/minio server /data --console-address ":9001"

version: "3.8"
services:
  nginx:
    image: 192.168.0.2:5050/dedyms/nginx:mainline
    hostname: nginx
    volumes:
      - ./nginx-std.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minio
    depends_on:
      - s3
    deploy:
      placement:
        constraints: [node.role == manager]

  s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    #restart: always
    #user: 1000:1000
    environment:
      - TZ=Asia/Jakarta
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
      - _MINIO_SERVER_DEBUG=on
    #ports:
    #  - 9000:9000
    #  - 9001:9001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data-standalone:/data
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - minio

  prometheus:
    image: prom/prometheus:v2.37.0
    user: 1000:1000
    networks:
      - minio
    environment:
      - TZ=Asia/Jakarta
      - PROMETHEUS_RETENTION=30d
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-24h}'
    volumes:
      - ./prometheus:/prometheus
      - /etc/localtime:/etc/localtime:ro
    configs:
      - source: prometheus_conf
        target: /etc/prometheus/prometheus.yml
#    ports:
#      - 14000:9090
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  minio:
    name: minio

configs:
 prometheus_conf:
    file: ./prometheus/prometheus.yml
