version: "3.8"
services:
  app:
    image: 192.168.0.2:5050/dedyms/unmanic:0.2.4
    restart: always
    runtime: crun
    group_add:
       - "44"
       - "139"
    volumes:
       - ./config:/home/debian/.unmanic
       - wd:/library
       - /dev/shm:/tmp/unmanic
    devices:
       - /dev/dri:/dev/dri
    ports:
       - 7777:8888
    networks:
       - unmanic
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  unmanic:
    name: unmanic

volumes:
  wd:
    driver_opts:
      type: "cifs"
      o: "addr=192.168.0.2,username=dedyms,password=smb,uid=1000,gid=1000,vers=3.0"
      device: "//192.168.0.2/datashare/Videos/MV"
