version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/unmanic:latest
    restart: always
    group_add:
       - video
       - render
    volumes:
       - ./config:/home/debian/.unmanic
       - cifs-wd:/library
       - /dev/shm:/tmp/unmanic
    devices:
       - /dev/dri:/dev/dri
    ports:
       - 7777:8888
    networks:
       - unmanic
    labels:
      - com.centurylinklabs.watchtower.enable=true
    #deploy:
    #  resources:
    #     limits:
    #       cpus: '4.0'
  #nginx:
  #  image: 192.168.0.2:5050/dedyms/nginx:mainline
  #  ports:
  #    - 7777:443
  #  volumes:
  #    - ./default.conf:/etc/nginx/conf.d/default.conf
  #  networks:
  #    - unmanic
  #apache:
  #  image: 192.168.0.2:5050/dedyms/apache2:fcgid
  #  ports:
  #    - 7777:443
  #  volumes:
  #    - ./apache.conf:/etc/apache2/sites-available/000-default-ssl.conf
  #  networks:
  #    - unmanic

networks:
  unmanic:
    name: unmanic

volumes:
  cifs-wd:
    driver_opts:
      type: "cifs"
      o: "addr=192.168.0.2,username=dedyms,password=smb,uid=1000,gid=1000"
      device: "//192.168.0.2/datashare/Videos/MV"
