version: "3.5"
services:
  diun:
    image: crazymax/diun:latest
#    user: 1000:1000
    volumes:
      - ./data:/data
      - ./data/diun.yml:/diun.yml:ro
      - ./data/image.yml:/image.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/dedyms/.docker:/root/.docker
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]