version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/stash:latest
    #command: /bin/bash
    #tty: true
    #stdin_open: true
    volumes:
      - ow_videos:/home/debian/stash/videos
      - /media/Clouds/Porn/Pictures:/home/debian/stash/pictures
      - config:/home/debian/stash
    ports:
      - 8888:9999
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]
    networks:
      - stash
volumes:
  ow_videos:
    external: true
  config:
networks:
  stash:
    name: stash
